export const quiz = {
  quizTitle: 'Knowledge Check',
  quizSynopsis: 'Let\'s check your understanding. Take a look at the feedback for each question you missed to make sure you understand everything before continuing.',
  questions: [
    {
      question: 'Every well-formed HTML document should include (at minimum):',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: ['doctype, head, body', 'doctype, header, body', 'header, nav, footer', 'alt text'],
      correctAnswer: '1',
      messageForCorrectAnswer: 'Correct answer. Good job.',
      messageForIncorrectAnswer: 'Incorrect answer. Please try again.',
      explanation: '',
      point: '1',
    },
    {
      question: 'Block-level elements begin on a new line.',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: ['True', 'False'],
      correctAnswer: '1',
      messageForCorrectAnswer: 'Correct answer. Good job.',
      messageForIncorrectAnswer: 'Incorrect answer. Please try again.',
      explanation: '',
      point: '1',
    },
    {
      question: 'A div element is an example of an inline-level element.',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: ['True', 'False'],
      correctAnswer: '2',
      messageForCorrectAnswer: 'Correct answer. Good job.',
      messageForIncorrectAnswer: 'Incorrect answer. Please try again.',
      explanation: '',
      point: '1',
    },
    {
      question: 'Which tag represents a line break (new line)?',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: ['<lb>', '<br/>', '<break>', '<line>'],
      correctAnswer: '2',
      messageForCorrectAnswer: 'Correct answer. Good job.',
      messageForIncorrectAnswer: 'Incorrect answer. Please try again.',
      explanation: '',
      point: '1',
    },
    {
      question: 'Which of the following are valid tags for HTML5 headings?',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: ['<heading>..</heading>', '<head>..</head>', '<h5>..</h5>', '<h7>..</h7>'],
      correctAnswer: '3',
      messageForCorrectAnswer: 'Correct answer. Good job.',
      messageForIncorrectAnswer: 'Incorrect answer. Please try again.',
      explanation: '',
      point: '1',
    },
    {
      question: 'All of the content you wish to appear on the screen should be in which tag?',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: ['<content>', '<html>', '<main>', '<body>'],
      correctAnswer: '4',
      messageForCorrectAnswer: 'Correct answer. Good job.',
      messageForIncorrectAnswer: 'Incorrect answer. Please try again.',
      explanation: '',
      point: '1',
    },
    {
      question: 'Which tag is used to create a link?',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: ['<anchor>', '<hyper>', '<a>', '<link>'],
      correctAnswer: '3',
      messageForCorrectAnswer: 'Correct answer. Good job.',
      messageForIncorrectAnswer: 'Incorrect answer. Please try again.',
      explanation: '',
      point: '1',
    },
    {
      question: 'Which HTML element is used to define list items?',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: ['<li>', '<item>', '<dl>', '<ul>'],
      correctAnswer: '1',
      messageForCorrectAnswer: 'Correct answer. Good job.',
      messageForIncorrectAnswer: 'Incorrect answer. Please try again.',
      explanation: '',
      point: '1',
    },
    {
      question: 'What should target = "_blank" do when included in a link?',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: ['Open an empty email', 'Open a page in a new browser window/tab', 'Create a blank browser page', 'Nothing'],
      correctAnswer: '2',
      messageForCorrectAnswer: 'Correct answer. Good job.',
      messageForIncorrectAnswer: 'Incorrect answer. Please try again.',
      explanation: '',
      point: '1',
    },
    {
      question: 'When should an image have null (empty) alt text (alt - “”)',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: ['When the image is black and white', 'When the image is complex', 'When the image is decorative', 'When the image already displays descriptive text'],
      correctAnswer: '3',
      messageForCorrectAnswer: 'Correct answer. Good job.',
      messageForIncorrectAnswer: 'Incorrect answer. Please try again.',
      explanation: '',
      point: '1',
    },
    {
      question: 'What are the two types of form methods?',
      questionType: 'text',
      answerSelectionType: 'multiple',
      answers: ['GET', 'ACTION', 'POST', 'FETCH'],
      correctAnswer: [1,3],
      messageForCorrectAnswer: 'Correct answer. Good job.',
      messageForIncorrectAnswer: 'Incorrect answer. Please try again.',
      explanation: '',
      point: '1',
    }
  ]
};
