export const quiz = {
  quizTitle: 'Knowledge Check',
  quizSynopsis: 'Let\'s check your understanding. Take a look at the feedback for each question you missed to make sure you understand everything before continuing.',
  questions: [
    {
      question: 'A "request" occurs when your computer asks another computer for some data.',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: ['True', 'False'],
      correctAnswer: '1',
      messageForCorrectAnswer: 'Correct answer. Good job.',
      messageForIncorrectAnswer: 'Incorrect answer. Please try again.',
      explanation: '',
      point: '1',
    },
    {
      question: 'Who is credited with creating the World Wide Web?',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: ['Ted Nelson', 'Tim Berners-Lee', 'Bill Atkinson', 'Vint Cerf'],
      correctAnswer: '2',
      messageForCorrectAnswer: 'Correct answer. Good job.',
      messageForIncorrectAnswer: 'Incorrect answer. Please try again.',
      explanation: '',
      point: '1',
    },
    {
      question: 'The first website was launched in ____ (year).',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: ['1986', '1990', '1991', '1995'],
      correctAnswer: '3',
      messageForCorrectAnswer: 'Correct answer. Good job.',
      messageForIncorrectAnswer: 'Incorrect answer. Please try again.',
      explanation: '',
      point: '1',
    },
    {
      question: 'In 2002, the W3C stated that HTML was finished. This led to the great schism of web developers. What was this drama about?',
      questionType: 'text',
      questionPic: '', // if you need to display Picture in Question
      answerSelectionType: 'single',
      answers: ['Some developers wanted to continue improving HTML while others wanted to switch to XHTML', 'They weren\'t sure who was going to work on HTML', 'Some developers wanted to use JavaScript instead of HTML', 'There weren\'t enough web browsers to support HTML'],
      correctAnswer: '1',
      messageForCorrectAnswer: 'Correct answer. Good job.',
      messageForIncorrectAnswer: 'Incorrect answer. Please try again.',
      explanation: '',
      point: '1',
    },
    {
      question: 'HTML5 is a conglomeration of which three languages?',
      questionType: 'text',
      answerSelectionType: 'multiple',
      answers: ['HTML', 'CSS', 'HTTP', 'JavaScript'],
      correctAnswer: [1,2,4],
      messageForCorrectAnswer: 'Correct answer. Good job.',
      messageForIncorrectAnswer: 'Incorrect answer. Please try again.',
      explanation: '',
      point: '1',
    },
    {
      question: 'What are the three main languages used in web development?',
      questionType: 'text',
      questionPic: '', // if you need to display Picture in Question
      answerSelectionType: 'single',
      answers: ['HTML, CSS, Java', 'XML, CSS, JavaScript', 'HTML, CSS, PHP', 'HTML, CSS, JavaScript'],
      correctAnswer: '4',
      messageForCorrectAnswer: 'Correct answer. Good job.',
      messageForIncorrectAnswer: 'Incorrect answer. Please try again.',
      explanation:
        '',
      point: '1',
    },
    {
      question: 'What can I find in the HTML Head section?',
      questionType: 'text',
      answerSelectionType: 'multiple',
      answers: ['metadata', 'body tag', 'title', 'charset'],
      correctAnswer: [1,3,4],
      messageForCorrectAnswer: 'Correct answer. Good job.',
      messageForIncorrectAnswer: 'Incorrect answer. Please try again.',
      explanation: '',
      point: '1',
    },
    {
      question: 'Everything in the body element will display in the browser',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: ['True', 'False'],
      correctAnswer: '1',
      messageForCorrectAnswer: 'Correct answer. Good job.',
      messageForIncorrectAnswer: 'Incorrect answer. Please try again.',
      explanation: '',
      point: '1',
    },
    {
      question: 'What is the minimum software needed to make a web page?',
      questionType: 'text',
      answerSelectionType: 'multiple',
      answers: ['Terminal', 'Web browser', 'Code editor', 'Computer'],
      correctAnswer: [2,3,4],
      messageForCorrectAnswer: 'Correct answer. Good job.',
      messageForIncorrectAnswer: 'Incorrect answer. Please try again.',
      explanation: '',
      point: '1',
    },
    {
      question: 'What tag is used to populate the browser bar in a web page?',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: ['meta', 'head', 'body', 'title'],
      correctAnswer: '4',
      messageForCorrectAnswer: 'Correct answer. Good job.',
      messageForIncorrectAnswer: 'Incorrect answer. Please try again.',
      explanation: '',
      point: '1',
    }
  ],
};
